name = "cloudflaresub"
main = "src/worker.js"
compatibility_date = "2026-03-06"
workers_dev = true

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*", "/sub/*"]

[[kv_namespaces]]
binding = "SUB_STORE"
id = "62681f7d81464876b1a38f3803ff8b49"
